version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./db:/app/db

  frontend:
    build:
      context: ../Nova_AEI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
